import { useCallback, useEffect, useState } from 'react'
import { ActivityIndicator, FlatList, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { useIsFocused } from '@react-navigation/native'
import { Archive, Bell, Check, Plus, Send, Users } from 'lucide-react-native'
import { api, type Broadcast, type BroadcastList, type ConnectedCustomer } from '../api'
import { EmptyState, Page, PrimaryButton } from './UI'
import { useAppColors } from '../theme'

function Header({ eyebrow, title }: { eyebrow: string; title: string }) {
  const c = useAppColors()
  return <View style={s.header}><Text style={[s.eyebrow, { color: c.accent }]}>{eyebrow}</Text><Text style={[s.title, { color: c.text }]}>{title}</Text></View>
}

export function BroadcastListsScreen({ token }: { token: string }) {
  const c = useAppColors(); const focused = useIsFocused()
  const [lists, setLists] = useState<BroadcastList[]>([]); const [customers, setCustomers] = useState<ConnectedCustomer[]>([])
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [name, setName] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { const [next, audience] = await Promise.all([api.broadcastLists(token), api.connectedCustomers(token)]); setLists(next); setCustomers(audience); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Could not load lists.') } finally { setLoading(false) } }, [token])
  useEffect(() => { if (focused) void load() }, [focused, load])
  const create = async () => { if (!name.trim() || saving) return; setSaving(true); try { await api.createBroadcastList(token, name.trim(), selected); setName(''); setSelected([]); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Could not create list.') } finally { setSaving(false) } }
  const remove = async (id: string) => { try { await api.deleteBroadcastList(token, id); setLists(v => v.filter(x => x.id !== id)) } catch (e) { setError(e instanceof Error ? e.message : 'Could not delete list.') } }
  return <Page><Header eyebrow="AUDIENCES" title="Broadcast lists"/>{error ? <Text style={[s.error, { color: c.danger }]}>{error}</Text> : null}
    {loading ? <View style={s.center}><ActivityIndicator color={c.accent}/></View> : <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
      <View style={[s.panel, { backgroundColor: c.surface, borderColor: c.border }]}><Text style={[s.panelTitle, { color: c.text }]}>Create a list</Text><TextInput value={name} onChangeText={setName} placeholder="List name" placeholderTextColor={c.muted} style={[s.input, { color: c.text, backgroundColor: c.surfaceAlt, borderColor: c.border }]}/>
        <Text style={[s.label, { color: c.muted }]}>CUSTOMERS · {selected.length} selected</Text>{customers.length ? customers.map(customer => <Pressable key={customer.id} onPress={() => setSelected(v => v.includes(customer.id) ? v.filter(id => id !== customer.id) : [...v, customer.id])} style={s.customer}><View style={[s.check, { borderColor: selected.includes(customer.id) ? c.accent : c.border, backgroundColor: selected.includes(customer.id) ? c.accent : 'transparent' }]}>{selected.includes(customer.id) ? <Check size={13} color="#fff"/> : null}</View><View style={{ flex: 1 }}><Text style={[s.customerName, { color: c.text }]}>{customer.name}</Text><Text style={[s.sub, { color: c.muted }]}>@{customer.username}</Text></View></Pressable>) : <Text style={[s.sub, { color: c.muted }]}>Connected customers will appear here.</Text>}
        <PrimaryButton title="Create list" icon={<Plus size={17} color="#fff"/>} loading={saving} disabled={!name.trim()} onPress={() => void create()}/>
      </View>
      <Text style={[s.section, { color: c.muted }]}>YOUR LISTS · {lists.length}</Text>
      {lists.length ? lists.map(list => <View key={list.id} style={[s.listRow, { backgroundColor: c.surface, borderColor: c.border }]}><View style={[s.iconBox, { backgroundColor: c.accentSoft }]}><Users color={c.accent} size={19}/></View><View style={{ flex: 1 }}><Text style={[s.panelTitle, { color: c.text }]}>{list.name}</Text><Text style={[s.sub, { color: c.muted }]}>{list.customerIds.length} customers</Text></View><Pressable onPress={() => void remove(list.id)} hitSlop={10}><Text style={{ color: c.danger, fontWeight: '700' }}>Delete</Text></Pressable></View>) : <Text style={[s.sub, { color: c.muted }]}>No broadcast lists yet.</Text>}
    </ScrollView>}</Page>
}

export function NewBroadcastScreen({ token }: { token: string }) {
  const c = useAppColors(); const focused = useIsFocused()
  const [lists, setLists] = useState<BroadcastList[]>([]); const [listId, setListId] = useState(''); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [status, setStatus] = useState('')
  useEffect(() => { if (!focused) return; let active = true; void api.broadcastLists(token).then(value => { if (active) { setLists(value); setListId(v => v || value[0]?.id || '') } }).catch(e => setStatus(e instanceof Error ? e.message : 'Could not load lists.')).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [focused, token])
  const send = async () => { if (!listId || !title.trim() || !body.trim() || sending) return; setSending(true); setStatus(''); try { await api.publishBroadcast(token, listId, title.trim(), body.trim()); setTitle(''); setBody(''); setStatus('Update sent to your selected audience.') } catch (e) { setStatus(e instanceof Error ? e.message : 'Could not send update.') } finally { setSending(false) } }
  return <Page><Header eyebrow="BUSINESS UPDATE" title="New broadcast"/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    {status ? <Text style={[s.notice, { color: status.includes('sent') ? c.success : c.danger }]}>{status}</Text> : null}
    {loading ? <ActivityIndicator color={c.accent}/> : lists.length ? <><Text style={[s.label, { color: c.muted }]}>SEND TO</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{lists.map(item => <Pressable key={item.id} onPress={() => setListId(item.id)} style={[s.chip, { backgroundColor: listId === item.id ? c.accent : c.surface, borderColor: listId === item.id ? c.accent : c.border }]}><Text style={{ color: listId === item.id ? '#fff' : c.text, fontWeight: '600' }}>{item.name}</Text></Pressable>)}</ScrollView>
      <Text style={[s.label, { color: c.muted }]}>TITLE</Text><TextInput value={title} onChangeText={setTitle} maxLength={100} placeholder="What's new?" placeholderTextColor={c.muted} style={[s.input, { color: c.text, backgroundColor: c.surface, borderColor: c.border }]}/>
      <Text style={[s.label, { color: c.muted, marginTop: 17 }]}>MESSAGE</Text><TextInput multiline value={body} onChangeText={setBody} maxLength={4000} textAlignVertical="top" placeholder="Write an update for your customers" placeholderTextColor={c.muted} style={[s.textarea, { color: c.text, backgroundColor: c.surface, borderColor: c.border }]}/><Text style={[s.sub, { color: c.muted, textAlign: 'right' }]}>{body.length}/4000</Text>
      <PrimaryButton title="Send update" icon={<Send size={17} color="#fff"/>} loading={sending} disabled={!title.trim() || !body.trim()} onPress={() => void send()}/></> : <EmptyState icon={<Users size={23} color={c.muted}/>} title="Create a list first" detail="Add connected customers to a broadcast list before sending an update."/>}
  </ScrollView></Page>
}

export function BroadcastFeedScreen({ token, business }: { token: string; business: boolean }) {
  const c = useAppColors(); const focused = useIsFocused(); const [items, setItems] = useState<Broadcast[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); try { const data = await api.broadcasts(token); setItems(data); setError(''); if (!business) await Promise.all(data.filter(x => !x.readAt).map(x => api.updateBroadcast(token, x.id, { read: true }).catch(() => undefined))) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load updates.') } finally { setLoading(false) } }, [token, business])
  useEffect(() => { if (focused) void load() }, [focused, load])
  const toggleSave = async (item: Broadcast) => { const saved = !item.saved; setItems(v => v.map(x => x.id === item.id ? { ...x, saved } : x)); try { await api.updateBroadcast(token, item.id, { saved }) } catch { void load() } }
  const toggleMute = async (item: Broadcast) => { const muted = !item.muted; setItems(v => v.map(x => x.id === item.id ? { ...x, muted } : x)); try { await api.muteBusiness(token, item.businessId, muted) } catch { void load() } }
  return <Page><Header eyebrow={business ? 'DELIVERY' : 'FROM YOUR BUSINESSES'} title={business ? 'Broadcast history' : 'Updates'}/>{error ? <Text style={[s.error, { color: c.danger }]}>{error}</Text> : null}
    {loading ? <View style={s.center}><ActivityIndicator color={c.accent}/></View> : items.length ? <FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={s.feed} renderItem={({ item }) => <View style={[s.broadcast, { backgroundColor: c.surface, borderColor: c.border }]}><View style={s.broadcastHead}><View style={[s.iconBox, { backgroundColor: c.accentSoft }]}><Bell color={c.accent} size={18}/></View><View style={{ flex: 1 }}><Text style={[s.panelTitle, { color: c.text }]}>{item.businessName || (business ? 'Sent update' : 'Business update')}</Text><Text style={[s.sub, { color: c.muted }]}>{new Date(item.publishedAt).toLocaleString()}</Text></View></View><Text style={[s.broadcastTitle, { color: c.text }]}>{item.title}</Text><Text style={[s.broadcastBody, { color: c.muted }]}>{item.body}</Text>{!business ? <View style={s.actions}><Pressable onPress={() => void toggleSave(item)}><Text style={{ color: c.accent, fontWeight: '700' }}>{item.saved ? 'Saved' : 'Save update'}</Text></Pressable><Pressable onPress={() => void toggleMute(item)}><Text style={{ color: c.muted, fontWeight: '600' }}>{item.muted ? 'Unmute business' : 'Mute business'}</Text></Pressable></View> : <View style={s.published}><Archive size={13} color={c.muted}/><Text style={[s.sub, { color: c.muted }]}>Published</Text></View>}</View>}/>: <EmptyState icon={<Bell size={23} color={c.muted}/>} title={business ? 'No broadcasts yet' : 'No business updates'} detail={business ? 'Your published updates will appear here.' : 'Updates from connected businesses will appear here.'}/>}</Page>
}

const s = StyleSheet.create({ header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 12 }, eyebrow: { fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, title: { fontSize: 26, fontWeight: '700', marginTop: 5 }, content: { paddingHorizontal: 16, paddingBottom: 28, gap: 14 }, panel: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 12 }, panelTitle: { fontSize: 15, fontWeight: '700' }, input: { minHeight: 48, borderWidth: 1, borderRadius: 13, paddingHorizontal: 13, fontSize: 14 }, textarea: { minHeight: 160, borderWidth: 1, borderRadius: 14, padding: 14, fontSize: 15, lineHeight: 22 }, label: { fontSize: 10, fontWeight: '800', letterSpacing: 0.8, marginTop: 5 }, customer: { flexDirection: 'row', alignItems: 'center', gap: 11, minHeight: 48 }, check: { width: 21, height: 21, borderRadius: 7, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' }, customerName: { fontSize: 14, fontWeight: '600' }, sub: { fontSize: 12, marginTop: 3 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, section: { fontSize: 10, fontWeight: '800', letterSpacing: 0.9, marginTop: 9 }, listRow: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 12, borderWidth: 1, borderRadius: 15 }, iconBox: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, chips: { gap: 8, paddingVertical: 2 }, chip: { borderWidth: 1, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 10 }, notice: { fontSize: 13, fontWeight: '600', marginHorizontal: 20, marginBottom: 8 }, error: { paddingHorizontal: 20, marginBottom: 8, fontSize: 13 }, feed: { paddingHorizontal: 14, paddingBottom: 24, gap: 10 }, broadcast: { borderWidth: 1, borderRadius: 17, padding: 15 }, broadcastHead: { flexDirection: 'row', alignItems: 'center', gap: 10 }, broadcastTitle: { fontSize: 18, fontWeight: '700', marginTop: 16 }, broadcastBody: { fontSize: 14, lineHeight: 21, marginTop: 7 }, actions: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#8884', marginTop: 14, paddingTop: 13 }, published: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 14 } })
